name: AVALaunch Enhancement Proposal
description: Submit an AEP
title: "[AEP]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a contribution to AVALaunch platform. Please state your AEP below
  - type: textarea
    id: proposal
    attributes:
      label: What is your enhancement or a feature request to the AVALaunch Platform?
      description: Provide as many details to your AEP as possible
      placeholder: Tell us what your AEP!
      value: "I would like to suggest [...]" or "In order to achieve [A], I require [B]"
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Is your AEP related to a problem? Please describe it
      description: Get into details of what is causing the problem for you
      placeholder: What is it?
      value: A clear and concise description of what the problem is. Ex. "I am always frustrated when [...]" or "The current functionality does not allow me to [...]"
    validations:
      required: false
