name: AVALaunch Enhancement Proposal
description: Submit an AEP
title: "[AEP]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a contribution to AVALaunch platform. Please state your AEP below
  - type: textarea
    id: proposal
    attributes:
      label: What is your enhancement or a feature request to the AVALaunch Platform?
      description: Provide as many details to your AEP as possible
      placeholder: Tell us what your AEP!
      value: I would like to suggest ... or In order to achieve A, I require B
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Is your AEP related to a problem? Please describe it
      description: Get into details of what is causing the problem for you
      placeholder: What is it?
      value: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] or The current functionality does not allow me to [...]
    validations:
      required: true  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like to reach
      description: Explain what is the best or acceptable solution for you and your team
      placeholder: What is it?
      value: A clear and concise description of what you want to happen.
    validations:
      required: true  
  - type: textarea
    id: alternatives
    attributes:
      label: Are there any alternative to your AEP?
      description: Provide the list of alternatives
      placeholder: List the all!
      value: A, B, C, D
    validations:
      required: true  
  - type: textarea
    id: testers
    attributes:
      label: Who will be participating in this AEP from your team?
      description: Tell us the names of AVALaunch Alpha testers
      placeholder: Provide email addresses
      value: Give us email addresses of your volunteers. Ex. yaroslav.zakahrov@raiffeisen.ua
    validations:
      required: true  
   - type: checkboxes
    id: reusable
    attributes:
      label: Can this AEP be useful for other teams/domains?
      description: Do you think someone else can benefit from it?
      options:
